-- ─────────────────────────────────────────────────────────────────────────
--  schema.sql — the Way2Buy schema on PostgreSQL (Supabase).
--
--  Applied on every boot and idempotent (CREATE ... IF NOT EXISTS), which is
--  what the SQLite migrate() did too. The same file runs against PGlite in the
--  test suite, so the tests exercise the real dialect.
--
--  Types are deliberate, not mechanical ports of the SQLite ones:
--    • money      → numeric(12,2). SQLite REAL is binary floating point; money
--                   in a float is a bug waiting for a rounding complaint.
--    • dates      → timestamptz. Everything the app writes is already UTC ISO.
--    • flags      → boolean.
--    • *_json     → jsonb, so the dashboard can query inside them.
--
--  Three columns keep their text type on purpose:
--    • customers.birthday — parseBirthday() accepts a year-less 'MM-DD', which
--      a date column cannot hold. See docs/BUSINESS-LOGIC.md §7.
--    • cart_events.ym / .y — pre-computed buckets. to_char() over a timestamptz
--      is not IMMUTABLE, so Postgres refuses to index it; these columns are how
--      the popularity reports stay indexable.
--    • events.meta — free text ('5 переглядів'), never JSON.
--
--  CHECK constraints are only on closed value sets. Columns like
--  notifications.kind or campaigns.status grow with the product (the scheduler
--  alone writes cost_missing_digest, inquiry_sent, bday_mismatch), so pinning
--  them would turn a new feature into a production insert failure.
-- ─────────────────────────────────────────────────────────────────────────

-- ── Customers & loyalty ──────────────────────────────────────────────────

create table if not exists customers (
  id                   integer primary key generated by default as identity,
  tg_user_id           text unique,
  login                text,
  name                 text not null,
  phone                text,
  email                text,
  -- 'YYYY-MM-DD' or a year-less 'MM-DD'. Text, not date: see the header.
  birthday             text,
  city                 text,
  address              text,
  birthday_source      text,                    -- 'claim' | 'admin' | 'seed'
  birthday_recorded_at timestamptz,
  consent              boolean not null default true,
  notes                text,
  created_at           timestamptz not null default now()
);

create table if not exists purchases (
  id               integer primary key generated by default as identity,
  customer_id      integer not null references customers(id) on delete cascade,
  title            text,
  -- what the client paid, normalised to USD — the only figure cashback reads
  amount_usd       numeric(12,2) not null,
  -- what the client actually saw (e.g. 60000 UAH), for the history screen
  orig_amount      numeric(14,2),
  orig_currency    text default 'USD',
  source_channel   text,
  invoice_ref      text,
  status           text default 'confirmed',
  -- the profit side: everything Maryna spent (factory + shipping + fees).
  -- Deliberately nullable — the sale is known now, the cost arrives later, and
  -- the scheduler chases the gap.
  cost_usd         numeric(12,2),
  cost_note        text,
  cost_entered_at  timestamptz,
  cost_reminded_at timestamptz,
  discount_usd     numeric(12,2) default 0,
  created_at       timestamptz not null default now()
);

create table if not exists redemptions (
  id          integer primary key generated by default as identity,
  customer_id integer not null references customers(id) on delete cascade,
  amount_usd  numeric(12,2) not null,
  note        text,
  created_at  timestamptz not null default now()
);

-- ── Channels & content ───────────────────────────────────────────────────

create table if not exists channels (
  id         integer primary key generated by default as identity,
  key        text not null unique,          -- slug used in posts.channel
  chat_id    text unique,                   -- numeric Telegram chat id (-100…)
  username   text,                          -- public @username, null if private
  title      text not null,
  emoji      text,
  kind       text not null default 'catalog' check (kind in ('main', 'catalog')),
  enabled    boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists posts (
  id             integer primary key generated by default as identity,
  channel        text not null,
  tg_message_id  bigint,
  title          text,
  body           text,
  price          numeric(12,2),
  currency       text default 'UAH',
  image_url      text,
  article        text,
  photos_json    jsonb,
  media_group_id text,
  brand          text,
  category       text,
  source         text not null check (source in ('app', 'channel')),
  -- 'gone' is not 'hidden'. Hidden is a human decision — Maryna took a card out
  -- of the vitrine. Gone is a fact — the channel no longer has that post. A sync
  -- sets the second and must never touch the first, or every sync would quietly
  -- undo her decisions.
  status         text default 'published' check (status in ('published', 'hidden', 'gone')),
  -- A human corrected what the parser guessed. The channel keeps supplying the
  -- text, the price and the photos, but the title, brand and category on a
  -- curated card are somebody's judgement and a sync leaves them alone.
  curated        boolean not null default false,
  edited_at      timestamptz,
  created_at     timestamptz not null default now()
);

-- ── changes to objects that already shipped ───────────────────────────────
--
-- CREATE TABLE IF NOT EXISTS cannot add a column to a table that exists, and it
-- does not fail either — it silently does nothing, so a database created before
-- these columns existed would keep running without them until a query broke.
-- Anything gained after the first deploy has to say so explicitly, the same rule
-- the index drops further down follow.
alter table posts    add column if not exists curated     boolean not null default false;
-- WHICH of the three sources named the brand — see parsePostText() and vision.js:
--   'text'        the caption said it. The seller's own word, right or wrong.
--   'channel'     the caption was silent and the catalogue's name answered.
--   'vision'      neither did, and the model read a logo off the photograph.
--   'vision-none' the model looked and found nothing legible. Recorded so the
--                 same photograph is not paid for twice.
--   null          nothing has answered yet — this is the backfill's work queue.
alter table posts    add column if not exists brand_source text;
alter table channels add column if not exists synced_at   timestamptz;
-- Where the deep backfill stopped, so «вся історія» resumes instead of re-reading
-- the newest pages. NULL means "start from the top".
alter table channels add column if not exists sync_cursor bigint;
-- Set once the walk reached the channel's first post; the button then has
-- nothing left to do.
alter table channels add column if not exists history_done boolean not null default false;
-- What was actually bought, as a card and not only as a line of text. Without
-- this a sale cannot be attributed to a brand, a category or a channel post, so
-- "which kind of thing sells" has to be guessed from the title. Nullable: sales
-- entered by hand, and every sale recorded before now, simply have no card.
alter table purchases add column if not exists post_id integer references posts(id) on delete set null;
alter table purchases add column if not exists article text;

do $$
begin
  -- The status CHECK is part of the table definition above, but a database
  -- created before 'gone' existed carries the old constraint (or none).
  if exists (select 1 from pg_constraint where conname = 'posts_status_check') then
    alter table posts drop constraint posts_status_check;
  end if;
  alter table posts add constraint posts_status_check
    check (status in ('published', 'hidden', 'gone'));
end $$;

create table if not exists events (
  id          integer primary key generated by default as identity,
  customer_id integer references customers(id) on delete set null,
  post_id     integer references posts(id) on delete set null,
  type        text not null,
  meta        text,                          -- free text, not JSON
  created_at  timestamptz not null default now()
);

-- ── Discounts, rules, campaigns ──────────────────────────────────────────

create table if not exists discount_rules (
  id            integer primary key generated by default as identity,
  key           text not null unique,        -- 'cashback' | 'birthday'
  kind          text not null,
  name          text not null,
  emoji         text,
  enabled       boolean not null default true,
  mode          text not null default 'fixed' check (mode in ('fixed', 'percent')),
  value         numeric(12,2) not null,      -- $ when mode='fixed', % when 'percent'
  min_order_usd numeric(12,2) default 0,
  cap_usd       numeric(12,2),               -- cashback: max unspent balance
  valid_days    integer,                     -- birthday: how long it lives
  updated_at    timestamptz not null default now(),
  updated_by    text
);

create table if not exists holidays (
  id              integer primary key generated by default as identity,
  name            text not null,
  month           integer not null check (month between 1 and 12),
  day             integer not null check (day between 1 and 31),
  emoji           text,
  default_percent integer default 15,
  enabled         boolean not null default true,
  mode            text not null default 'percent' check (mode in ('fixed', 'percent')),
  value           numeric(12,2),
  min_order_usd   numeric(12,2) default 0,
  valid_days      integer default 14,
  created_at      timestamptz not null default now()
);

create table if not exists campaigns (
  id               integer primary key generated by default as identity,
  name             text not null,
  type             text not null,            -- birthday | holiday | vip | generic
  percent          integer not null,
  audience_json    jsonb,                    -- {tier?, minSpentUsd?, city?, …}
  holiday_id       integer references holidays(id) on delete set null,
  starts_at        timestamptz,               -- null = immediate
  ends_at          timestamptz,               -- null = open-ended
  recurring        boolean not null default false,
  window_days      integer default 0,
  promo_valid_days integer default 14,
  status           text default 'draft',      -- draft|scheduled|active|ended|archived
  source           text default 'manual',
  created_by       text,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

-- Who may open the cabinet, and how far in.
--
-- This used to be ADMIN_TG_IDS, an environment variable — which meant appointing
-- somebody was a deploy, and a role was a boolean. It is a table because the
-- owner must be able to add and remove people herself, and because "manager"
-- and "owner" are not the same job: one answers clients, the other sets the
-- prices and the discounts.
--
-- ADMIN_TG_IDS survives as the bootstrap: anyone named there is a super admin
-- regardless of this table, so an empty or mistakenly emptied table can never
-- lock everybody out of their own shop.
create table if not exists admins (
  id          integer primary key generated by default as identity,
  tg_user_id  text not null unique,
  name        text,
  role        text not null default 'admin' check (role in ('super', 'admin')),
  enabled     boolean not null default true,
  note        text,
  created_at  timestamptz not null default now(),
  created_by  text
);

-- A campaign was percent-only while every other discount in the app is either a
-- sum or a percentage. `percent` stays as it is — older rows and older clients
-- still read it — and mode/value are what everything written from here on uses.
alter table campaigns add column if not exists mode          text not null default 'percent';
alter table campaigns add column if not exists value         numeric(12,2);
alter table campaigns add column if not exists min_order_usd numeric(12,2) default 0;
-- Which preset the super admin started from, kept so the cabinet can say
-- «Різдвяна знижка» rather than re-deriving it from a set of conditions.
alter table campaigns add column if not exists preset        text;

create table if not exists promo_codes (
  id            integer primary key generated by default as identity,
  customer_id   integer references customers(id) on delete cascade,
  campaign_id   integer references campaigns(id) on delete set null,
  code          text not null unique,
  percent       integer not null default 0,
  mode          text not null default 'percent' check (mode in ('fixed', 'percent')),
  amount_usd    numeric(12,2),
  min_order_usd numeric(12,2) default 0,
  rule_key      text,
  reason        text,
  status        text default 'active',
  created_at    timestamptz not null default now(),
  expires_at    timestamptz
);

-- One-off automatic discounts, and the fact that somebody has already had one.
--
-- «Додав у примірочну і не написав менеджеру за 5 годин → 10%» must fire once
-- per person and never again, and the shop will invent more rules like it. A
-- column per rule would mean a migration every time somebody has an idea, so
-- the rule's own name is the KEY — '5hour_10per' reads the same in the database
-- as it does in the conversation — and the UNIQUE index is what makes "already
-- had it" a fact the database enforces rather than something the code checks
-- and races on.
create table if not exists customer_grants (
  id            integer primary key generated by default as identity,
  customer_id   integer not null references customers(id) on delete cascade,
  grant_key     text not null,               -- '5hour_10per'
  promo_code_id integer references promo_codes(id) on delete set null,
  granted_at    timestamptz not null default now(),
  meta          jsonb
);

create table if not exists birthday_claims (
  id               integer primary key generated by default as identity,
  customer_id      integer not null references customers(id) on delete cascade,
  claimed_birthday text,                     -- what the client entered
  on_file_birthday text,                     -- what we already had
  year             integer not null,
  verdict          text not null check (verdict in (
                     'granted', 'mismatch', 'already_claimed',
                     'out_of_window', 'disabled', 'invalid_date')),
  promo_code_id    integer references promo_codes(id) on delete set null,
  note             text,
  created_at       timestamptz not null default now()
);

-- ── Fitting room, demand, inquiries ──────────────────────────────────────

create table if not exists inquiries (
  id            integer primary key generated by default as identity,
  customer_id   integer not null references customers(id) on delete cascade,
  message       text,
  items_json    jsonb not null,
  items_count   integer not null default 0,
  promo_code_id integer references promo_codes(id) on delete set null,
  promo_label   text,
  status        text not null default 'new',
  answered_by   text,
  answered_at   timestamptz,
  created_at    timestamptz not null default now()
);

-- ── Did they actually buy it? ────────────────────────────────────────────
--
--  An inquiry answers "who asked about what". It does not answer the question
--  the shop actually lives on: did that person go on to buy the article, or
--  not? Nothing recorded that before, so the answer lived in Maryna's head.
--
--  One row per inquiry, opened the moment the client presses «Відправити».
--  It starts `in_progress` and stays there until a human says otherwise —
--  «no answer yet» is a real state, not an absence of data, and it is the one
--  the reminder job reads.
--
--  Maryna asked for three columns — in progress / bought / not bought — so the
--  table can be read at a glance in the Supabase editor. They are here, but
--  GENERATED from `status`: three independent booleans can be set to two trues
--  or three falses, and then no query in the app agrees with any other. One
--  writable column decides; the three read exactly as asked and cannot drift.
--  Correcting a mistake is therefore a single UPDATE of `status`, which is what
--  the pencil in the cabinet does.
create table if not exists deals (
  id            integer primary key generated by default as identity,
  customer_id   integer not null references customers(id) on delete cascade,
  -- The inquiry this grew out of. Kept unique so a re-sent request cannot open
  -- a second card for the same conversation.
  inquiry_id    integer references inquiries(id) on delete set null,
  -- Snapshot of the articles asked about, so a post edited or deleted in the
  -- channel never rewrites what the deal was about. Same reasoning as
  -- cart_events.
  items_json    jsonb not null default '[]'::jsonb,
  items_count   integer not null default 0,
  articles      text,                        -- 'CH22, DL01' — for search and DMs
  status        text not null default 'in_progress'
                check (status in ('in_progress', 'bought', 'not_bought')),
  in_progress   boolean generated always as (status = 'in_progress') stored,
  bought        boolean generated always as (status = 'bought')      stored,
  not_bought    boolean generated always as (status = 'not_bought')  stored,
  -- Optional, and only meaningful once bought: what the order came to. The
  -- money of record is still `purchases`; this is the manager's own note.
  amount_usd    numeric(12,2),
  note          text,
  decided_by    text,                        -- tg id of whoever moved it
  decided_at    timestamptz,
  -- The nudge loop. `reminders` is the round number, so the dedupe key of the
  -- next reminder is different from the last one's without a timer anywhere.
  reminded_at   timestamptz,
  reminders     integer not null default 0,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create table if not exists cart_items (
  id          integer primary key generated by default as identity,
  customer_id integer not null references customers(id) on delete cascade,
  post_id     integer references posts(id) on delete set null,
  title       text,
  article     text,
  channel     text,
  photo       text,                          -- file_id or emoji, snapshot
  price       numeric(12,2),
  currency    text,
  note        text,
  status      text not null default 'active' check (status in ('active', 'sent')),
  inquiry_id  integer references inquiries(id) on delete set null,
  created_at  timestamptz not null default now(),
  sent_at     timestamptz
);

-- Append-only journal. Every popularity figure reads only this table, and it
-- keeps a snapshot of the item, so a post edited or deleted in the channel does
-- not rewrite history.
create table if not exists cart_events (
  id          integer primary key generated by default as identity,
  customer_id integer references customers(id) on delete set null,
  post_id     integer references posts(id) on delete set null,
  action      text not null check (action in ('added', 'removed', 'sent')),
  title       text,
  article     text,
  channel     text,
  price_usd   numeric(12,2),
  inquiry_id  integer references inquiries(id) on delete set null,
  created_at  timestamptz not null default now(),
  ym          text not null,                 -- 'YYYY-MM' — see the header
  y           text not null                  -- 'YYYY'
);

-- ── Comms ────────────────────────────────────────────────────────────────

create table if not exists notifications (
  id            integer primary key generated by default as identity,
  customer_id   integer references customers(id) on delete cascade,
  kind          text not null,
  title         text not null,
  body          text,
  promo_code_id integer references promo_codes(id) on delete set null,
  campaign_id   integer references campaigns(id) on delete set null,
  -- the whole reason a re-run of the scheduler is a no-op
  dedupe_key    text not null unique,
  in_app_status text default 'unread' check (in_app_status in ('unread', 'read')),
  dm_status     text default 'pending',
  created_at    timestamptz not null default now(),
  read_at       timestamptz
);

-- ── AI agent ─────────────────────────────────────────────────────────────

create table if not exists ai_conversations (
  id          integer primary key generated by default as identity,
  admin_tg_id text not null,
  title       text,
  created_at  timestamptz not null default now(),
  last_at     timestamptz
);

create table if not exists ai_messages (
  id              integer primary key generated by default as identity,
  conversation_id integer references ai_conversations(id) on delete cascade,
  role            text not null,             -- user | assistant | tool
  content         text,
  tool_name       text,
  tool_args_json  jsonb,
  created_at      timestamptz not null default now()
);

create table if not exists ai_proposals (
  id              integer primary key generated by default as identity,
  conversation_id integer references ai_conversations(id) on delete cascade,
  tool_name       text not null,
  args_json       jsonb not null,
  summary         text not null,             -- Ukrainian, shown to the admin
  status          text default 'pending',
  created_at      timestamptz not null default now(),
  applied_at      timestamptz
);

-- ── Infrastructure ───────────────────────────────────────────────────────

create table if not exists scheduler_lock (
  id           integer primary key check (id = 1),
  holder       text,
  heartbeat_at timestamptz
);

-- Anti-pause heartbeat for the Free plan. Also created by
-- scripts/sql/keepalive.sql, which additionally installs the RPC the cron calls.
create table if not exists heartbeat (
  id      integer primary key default 1 constraint heartbeat_single_row check (id = 1),
  seen_at timestamptz not null default now(),
  hits    bigint not null default 0
);

-- ─────────────────────────────────────────────────────────────────────────
--  Indexes — derived from the queries the app actually runs, not from the
--  column list. Every one below has a call site.
-- ─────────────────────────────────────────────────────────────────────────

-- loyalty snapshotBatch / purchase history: per-customer aggregates and lists
create index if not exists idx_purchases_customer      on purchases (customer_id, created_at desc);
create index if not exists idx_purchases_status        on purchases (customer_id, status);
-- profit report: a date window, optionally narrowed to one channel
create index if not exists idx_purchases_created       on purchases (created_at desc);
create index if not exists idx_purchases_channel_date  on purchases (source_channel, created_at desc);
-- pendingCosts(): "sold over a day ago, cost still missing". A partial index is
-- the whole working set — it holds only the rows the query wants, and empties
-- itself as costs get entered.
create index if not exists idx_purchases_cost_missing  on purchases (created_at)
  where cost_usd is null;

create index if not exists idx_redemptions_customer    on redemptions (customer_id);

-- feed: one channel, newest first; and the merged feed across channels.
--
-- `id desc` is part of the key, not decoration. The vitrine pages by keyset on
-- (created_at, id) — created_at alone is not unique, because an album of eight
-- photos is posted in one second — and a cursor can only be resolved by an index
-- that carries both columns in the ORDER BY's own order.
--
-- Dropping the two-column versions is deliberate: these indexes shipped before
-- paging existed, and CREATE ... IF NOT EXISTS cannot widen an index that is
-- already there. Leaving both would pay for two copies of the same thing.
drop index if exists idx_posts_channel_created;
drop index if exists idx_posts_created;
create index if not exists idx_posts_channel_created   on posts (channel, created_at desc, id desc);
create index if not exists idx_posts_created           on posts (created_at desc, id desc);
-- the content filters: brand and category are whatever the parser found, so
-- these are the columns /api/facets groups by. Partial, because most of a
-- catalogue's prose yields neither.
create index if not exists idx_posts_brand             on posts (brand, created_at desc)
  where brand is not null and status = 'published';
create index if not exists idx_posts_category          on posts (category, created_at desc)
  where category is not null and status = 'published';
-- The vision backfill's work queue: published cards nobody has named a brand for
-- yet. Partial and tiny — it shrinks to nothing as the queue is worked off, which
-- is the point: without it every scheduler tick seq-scans all 6.7k posts to find
-- the handful left.
create index if not exists idx_posts_brand_pending     on posts (created_at desc)
  where brand_source is null and status = 'published';
-- channel_post webhook: find the row a Telegram edit refers to
create unique index if not exists uq_posts_channel_msg on posts (channel, tg_message_id)
  where tg_message_id is not null;
-- album grouping (a forwarded post arrives as N media_group messages)
create index if not exists idx_posts_media_group       on posts (channel, media_group_id)
  where media_group_id is not null;
create index if not exists idx_posts_article           on posts (article) where article is not null;

-- search: ?q= is an ILIKE '%…%', which no b-tree can serve. Trigram GIN turns it
-- into an index scan — irrelevant while a catalogue holds dozens of cards,
-- decisive once it holds tens of thousands.
--
-- ONE index over the three columns concatenated, matching the expression in
-- catalog.js (SEARCH_EXPR). Per-column indexes were the obvious thing and they
-- were useless: the query ORs title/body/article together, and Postgres can only
-- use indexes for an OR when every branch has one — so it scanned the table
-- anyway. Concatenating makes it a single indexable condition. Change either
-- side and this index stops being used, silently.
--
-- Guarded, and the only guarded index in this file: pg_trgm ships with Postgres
-- and with Supabase but not with the PGlite build the tests run on. The
-- condition is what lets one schema file stay the single truth for both. The
-- operator class is schema-qualified because Supabase keeps extensions out of
-- `public`, and an unqualified gin_trgm_ops would then not resolve.
do $$
declare ext_schema text;
begin
  if not exists (select 1 from pg_available_extensions where name = 'pg_trgm') then return; end if;

  if exists (select 1 from pg_namespace where nspname = 'extensions')
    then create extension if not exists pg_trgm with schema extensions;
    else create extension if not exists pg_trgm;
  end if;

  select n.nspname into ext_schema
    from pg_extension e join pg_namespace n on n.oid = e.extnamespace
   where e.extname = 'pg_trgm';

  -- The per-column pair shipped before the OR problem was understood.
  drop index if exists idx_posts_title_trgm;
  drop index if exists idx_posts_body_trgm;

  execute format($fmt$
    create index if not exists idx_posts_search_trgm on posts using gin (
      (coalesce(title,'') || ' ' || coalesce(body,'') || ' ' || coalesce(article,'')) %I.gin_trgm_ops
    )$fmt$, ext_schema);
end $$;

create index if not exists idx_events_customer         on events (customer_id, created_at desc);
create index if not exists idx_events_post             on events (post_id);
create index if not exists idx_events_type             on events (type, created_at desc);

-- resolveChannel(): a channel is matched by @username on its first post, then
-- its numeric chat_id is bound. lower() because Telegram usernames are
-- case-insensitive, and it is immutable so it can carry an index.
--
-- NOT unique: two rows legitimately share a username. The 'main' channel and the
-- legacy 'ukraine' catalogue both default to @Way2Buy_Ukraine, so a unique index
-- here fails on a clean seed.
--
-- The drop is deliberate. An earlier version of this file made the index UNIQUE,
-- and a file built out of CREATE ... IF NOT EXISTS cannot correct an object that
-- already exists — re-applying it would silently leave the old constraint in
-- place, and inserts would keep failing. Any statement that changes a previously
-- shipped object has to say so explicitly, like this one.
drop index if exists uq_channels_username_lower;
create index if not exists idx_channels_username_lower on channels (lower(username))
  where username is not null;
create index if not exists idx_channels_enabled        on channels (enabled, kind);

-- the client's discount wallet, and the admin's per-customer view
create index if not exists idx_promo_customer          on promo_codes (customer_id, status);
create index if not exists idx_promo_campaign          on promo_codes (campaign_id);
-- Idempotent materialisation (R-02): exactly one code per customer per campaign
-- per calendar year. The year is derived at UTC because that is the clock the
-- app writes in; `at time zone` on a literal zone is immutable, so this is
-- indexable — extract() straight off a timestamptz is not.
create unique index if not exists uq_promo_campaign_customer_year
  on promo_codes (campaign_id, customer_id,
                  extract(year from (created_at at time zone 'UTC')))
  where campaign_id is not null;

-- scheduler reconcileStatus(): scans by status inside a date window
create index if not exists idx_campaigns_status_dates  on campaigns (status, starts_at, ends_at);
create index if not exists idx_campaigns_type          on campaigns (type, status);

create index if not exists idx_holidays_date           on holidays (month, day);

create index if not exists idx_bday_claims_customer    on birthday_claims (customer_id, year);
-- One GRANTED birthday discount per customer per year. Non-granted verdicts are
-- still logged and do not collide.
create unique index if not exists uq_bday_granted_year on birthday_claims (customer_id, year)
  where verdict = 'granted';
create index if not exists idx_bday_claims_verdict     on birthday_claims (verdict, created_at desc);

create index if not exists idx_cart_customer           on cart_items (customer_id, status);
-- The same post cannot sit twice in one fitting room.
create unique index if not exists uq_cart_active       on cart_items (customer_id, post_id)
  where status = 'active';

create index if not exists idx_cart_events_ym          on cart_events (ym, action);
create index if not exists idx_cart_events_y           on cart_events (y, action);
create index if not exists idx_cart_events_post        on cart_events (post_id, action);
create index if not exists idx_cart_events_channel     on cart_events (channel, action);
create index if not exists idx_cart_events_created     on cart_events (created_at desc);
-- The monthly funnel groups by month AND counts distinct people, so the month
-- bucket and the customer travel together.
create index if not exists idx_cart_events_ym_customer on cart_events (ym, action, customer_id);
-- THE constraint the "once, ever" promise rests on. abandoned.js inserts before
-- it sends and relies on ON CONFLICT here, so a racing tick loses the insert
-- instead of sending a second discount.
create unique index if not exists uq_customer_grant on customer_grants (customer_id, grant_key);
create index if not exists idx_customer_grants_key   on customer_grants (grant_key);
-- Covers the FK: deleting a promo code has to check every grant that points at
-- it, and without this that check is a seq scan of the whole grants table.
create index if not exists idx_customer_grants_promo on customer_grants (promo_code_id) where promo_code_id is not null;
create index if not exists idx_purchases_post        on purchases (post_id) where post_id is not null;

create index if not exists idx_inquiries_status        on inquiries (status, created_at desc);
create index if not exists idx_inquiries_customer      on inquiries (customer_id, created_at desc);

-- The three tabs of the «Покупки» section are this one index.
create index if not exists idx_deals_status            on deals (status, created_at desc);
create index if not exists idx_deals_customer          on deals (customer_id, created_at desc);
-- What the reminder job scans every tick: only the open ones, oldest first.
create index if not exists idx_deals_open              on deals (coalesce(reminded_at, created_at))
  where status = 'in_progress';
-- One deal per inquiry. This is what makes openDeal() idempotent, so a retried
-- send cannot produce two cards for one conversation. Not partial on purpose:
-- Postgres already allows any number of NULLs in a unique index, and a partial
-- one could not be named by the plain `ON CONFLICT (inquiry_id)` that openDeal
-- relies on.
create unique index if not exists uq_deals_inquiry     on deals (inquiry_id);

-- the client's notification feed, and the unread badge
create index if not exists idx_notifications_customer  on notifications (customer_id, created_at desc);
create index if not exists idx_notifications_unread    on notifications (customer_id)
  where in_app_status = 'unread';

create index if not exists idx_ai_conv_admin           on ai_conversations (admin_tg_id, last_at desc);
create index if not exists idx_ai_messages_conv        on ai_messages (conversation_id, id);
create index if not exists idx_ai_proposals_conv       on ai_proposals (conversation_id, status);

-- birthdaysToday(): matches the MM-DD slice of a stored 'YYYY-MM-DD'. substr()
-- over text is immutable, so unlike a date column this stays indexable — one of
-- the reasons birthday keeps its text type.
create index if not exists idx_customers_birthday_mmdd on customers (substr(birthday, 6, 5))
  where birthday is not null;

-- Foreign keys with no covering index. No query below reads them directly, but
-- Postgres does: every ON DELETE CASCADE / SET NULL has to find the child rows,
-- and without an index that is a sequential scan of the child table. Deleting one
-- customer would scan cart_events; retiring one promo code would scan
-- notifications. Partial, because the point is only to find the non-null links.
create index if not exists idx_bday_claims_promo   on birthday_claims (promo_code_id) where promo_code_id is not null;
create index if not exists idx_campaigns_holiday   on campaigns (holiday_id)          where holiday_id is not null;
create index if not exists idx_cart_events_customer on cart_events (customer_id)      where customer_id is not null;
create index if not exists idx_cart_events_inquiry on cart_events (inquiry_id)        where inquiry_id is not null;
create index if not exists idx_cart_items_inquiry  on cart_items (inquiry_id)         where inquiry_id is not null;
create index if not exists idx_cart_items_post     on cart_items (post_id)            where post_id is not null;
create index if not exists idx_inquiries_promo     on inquiries (promo_code_id)       where promo_code_id is not null;
create index if not exists idx_notifications_campaign on notifications (campaign_id)  where campaign_id is not null;
create index if not exists idx_notifications_promo on notifications (promo_code_id)   where promo_code_id is not null;

-- ─────────────────────────────────────────────────────────────────────────
--  Views — read-only, for browsing the data in the Supabase table editor and
--  for ad-hoc reporting. The application does not depend on them: business
--  logic stays in the server modules, where the tests can reach it.
-- ─────────────────────────────────────────────────────────────────────────

create or replace view v_customer_overview
  with (security_invoker = true) as
select
  c.id,
  c.name,
  c.login,
  c.city,
  c.birthday,
  count(p.id)                                        as purchase_count,
  coalesce(sum(p.amount_usd), 0)                     as spent_usd,
  coalesce(sum(p.amount_usd) filter (where p.amount_usd >= 2000), 0) as qualifying_usd,
  coalesce((select sum(r.amount_usd) from redemptions r where r.customer_id = c.id), 0) as redeemed_usd,
  max(p.created_at)                                  as last_purchase_at,
  c.created_at
from customers c
left join purchases p on p.customer_id = c.id and p.status = 'confirmed'
group by c.id;

comment on view v_customer_overview is
  'Per-customer spend rollup for browsing. Cashback and tiers are computed in server/loyalty.js — this view is not the source of truth for them.';

create or replace view v_purchase_margin
  with (security_invoker = true) as
select
  p.id,
  p.customer_id,
  c.name as customer_name,
  p.title,
  p.amount_usd,
  p.cost_usd,
  case when p.cost_usd is null then null
       else p.amount_usd - p.cost_usd - coalesce(p.discount_usd, 0) end as margin_usd,
  case when p.cost_usd is null or p.amount_usd = 0 then null
       else round(((p.amount_usd - p.cost_usd - coalesce(p.discount_usd, 0)) / p.amount_usd) * 100, 1)
  end as margin_pct,
  p.cost_usd is null as cost_pending,
  p.source_channel,
  p.created_at
from purchases p
join customers c on c.id = p.customer_id;

comment on view v_purchase_margin is
  'Sale vs factory cost per order. cost_pending marks the rows the scheduler is still chasing.';

create or replace view v_item_popularity
  with (security_invoker = true) as
select
  ce.post_id,
  ce.title,
  ce.article,
  ce.channel,
  ce.ym,
  count(*) filter (where ce.action = 'added')   as adds,
  count(*) filter (where ce.action = 'sent')    as sends,
  count(*) filter (where ce.action = 'removed') as removes,
  count(distinct ce.customer_id)                as people
from cart_events ce
group by ce.post_id, ce.title, ce.article, ce.channel, ce.ym;

comment on view v_item_popularity is
  'What was tried on, by month. Reads the append-only journal, so it survives posts being edited or deleted.';

-- ─────────────────────────────────────────────────────────────────────────
--  Table documentation — shows up in the Supabase table editor.
-- ─────────────────────────────────────────────────────────────────────────

comment on table customers       is 'Club members. Identity comes from Telegram (tg_user_id); everything else is what Maryna or the client entered.';
comment on table purchases       is 'Confirmed sales. amount_usd is what the client paid; cost_usd is what the order cost, entered later.';
comment on table redemptions     is 'Cashback spent. Balance = earned (from purchases) − redeemed.';
comment on table channels        is 'Telegram channels as data: one main channel plus the catalogues. chat_id is learned from the first post.';
comment on table posts           is 'Unified feed. source=app means published from the admin office; source=channel means pulled in by the webhook.';
comment on table events          is 'Behavioural signals (view/want/return/join) feeding retention and the AI reports.';
comment on table discount_rules  is 'The bonus rules the admin edits: $ or %, minimum order, cap, validity. Editing a promotion must not mean editing code.';
comment on table holidays        is 'Recurring holiday calendar (MM-DD), configured like any other rule.';
comment on table campaigns       is 'Scheduled discount campaigns; materialise() turns one into concrete per-customer promo codes.';
comment on table promo_codes     is 'Issued discounts, percent or fixed amount, optionally linked to the campaign that generated them.';
comment on table birthday_claims is 'Audit log of every birthday-discount request, granted or not, so a second request can be cross-checked against the date on file.';
comment on table inquiries       is 'What a client sent from the fitting room: their own text plus a snapshot of the items.';
comment on table deals           is 'Did the client who asked about an article go on to buy it? One row per inquiry: in_progress until a manager says bought or not_bought.';
comment on table cart_items      is 'The fitting room itself — short-lived, cleared when the inquiry is sent.';
comment on table cart_events     is 'Append-only journal of fitting-room actions. Never deleted; all popularity reporting reads only this.';
comment on table notifications   is 'In-app notification feed and DM delivery state. dedupe_key makes a scheduler re-run a no-op.';
comment on table ai_conversations is 'Admin conversations with the reporting agent.';
comment on table ai_messages     is 'Transcript of an AI conversation.';
comment on table ai_proposals    is 'An action the agent proposed; applied only after the admin confirms.';
comment on table scheduler_lock  is 'Single-row advisory lock so two processes cannot tick at once.';
comment on table heartbeat       is 'Anti-pause heartbeat: the Free plan pauses a project after ~7 days without user database activity.';

comment on column customers.birthday is
  'Text, not date: a year-less MM-DD is a valid stored value (parseBirthday()).';
comment on column cart_events.ym is
  'Pre-computed YYYY-MM bucket. to_char() over timestamptz is not IMMUTABLE and cannot be indexed, which is why this column exists.';
comment on column purchases.cost_usd is
  'Nullable on purpose: the sale is known now, the factory cost arrives later.';
comment on column deals.in_progress is
  'Generated from status, never written directly — three independent booleans could disagree with each other; one status column cannot.';

-- ─────────────────────────────────────────────────────────────────────────
--  Access posture. Every query in this app goes through the Express server
--  using the service_role key, so no table is meant to be reachable with the
--  public anon key. RLS on with zero policies denies anon and authenticated
--  outright, while service_role bypasses RLS — deny-by-default rather than a
--  policy someone has to remember to write.
--
--  The role grants are wrapped in a guard because anon/authenticated exist only
--  on Supabase; the same file has to run against PGlite in the tests.
-- ─────────────────────────────────────────────────────────────────────────

do $$
declare t text;
begin
  foreach t in array array[
    'customers', 'purchases', 'redemptions', 'channels', 'posts', 'events',
    'discount_rules', 'holidays', 'campaigns', 'promo_codes', 'birthday_claims',
    'inquiries', 'deals', 'cart_items', 'cart_events', 'notifications',
    'ai_conversations', 'ai_messages', 'ai_proposals', 'scheduler_lock',
    -- `admins` is the roster of who may run the shop. A table left out of this
    -- list keeps Supabase's default grants, which hand the public anon key full
    -- read and write — and this is the last table in the database that should
    -- have them.
    'admins', 'customer_grants',
    'heartbeat'
  ]
  loop
    execute format('alter table %I enable row level security', t);
    if exists (select 1 from pg_roles where rolname = 'anon') then
      execute format('revoke all on table %I from anon, authenticated', t);
    end if;
  end loop;

  -- The views run with the privileges of their owner, so they must not be a
  -- way around the tables' RLS for a public key either.
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on v_customer_overview, v_purchase_margin, v_item_popularity'
         || ' from anon, authenticated';
  end if;
end $$;
